### ISSUE TITLE
推送  firim

### ISSUE THREAD

**Issue by ChengGPBU** [msdx/fir-publisher#3]
您好  
![image](https://user-images.githubusercontent.com/24949641/50633724-55714900-0f87-11e9-9299-2b01ecc4eb3c.png)  
我这么写的时候  默认将release 版本的包  推送到firim上去了
怎么配置  才能上传 我指定的包  比如 debug包

**Comment by msdx** [comment]
@ChengGPBU 本插件只会传release包。如果需要传debug包，需要自己改。
在你的项目根目录中新建buildSrc文件夹，把src及build.gradle复制到该文件夹下。
修改FirPlugin.groovy，把第91,92行的`Release`改为`Debug`。
原来根项目下的build.gradle的classpath里不需要再声明fir插件。

**Comment by ChengGPBU** [comment]
感谢  感谢！
